[build]
  base = "reddit"
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "v18.15.0"  # Replace with your Node.js version

[dev]
  command = "node backend/index.js"  # Adjust this based on your local development setup
