[build]
  base = "reddit"
  command = "npm run build"
  publish = "reddit/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "your_node_version"  # Replace with your Node.js version

[dev]
  command = "node index.js"  # Adjust this based on your local development setup
