[build]
  base = "reddit-clone/reddit"  # Path to your frontend directory
  command = "npm run build"    # Build command for the frontend
  functions = "reddit-clone/backend"  # Path to your backend serverless functions directory

[dev]
  command = "nodemon index.js"  # Command to run during local development, adjust based on your setup