[build]
  base = "reddit"  # Path to your frontend directory
  command = "npm run build"    # Build command for the frontend
  functions = "backend"  # Path to your backend serverless functions directory
  publish = "reddit/public"

[dev]
  command = "nodemon index.js"  # Command to run during local development, adjust based on your setup